In [4]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/tugasuas/Jan_2019_ontime.csv


In [5]:
import warnings

warnings.filterwarnings('ignore')

In [6]:
#mengimport dataset

df = pd.read_csv("../input/tugasuas/Jan_2019_ontime.csv")
df.shape

(583985, 19)

In [7]:
df.head() #digunakan untuk menampilkan record pertama dari dataframe

DAY_OF_MONTH  DAY_OF_WEEK OP_UNIQUE_CARRIER  OP_CARRIER_AIRLINE_ID  \
0             1            2                9E                  20363   
1             1            2                9E                  20363   
2             1            2                9E                  20363   
3             1            2                9E                  20363   
4             1            2                9E                  20363   

  OP_CARRIER TAIL_NUM  OP_CARRIER_FL_NUM  ORIGIN_AIRPORT_ID ORIGIN  \
0         9E   N8688C               3280              11953    GNV   
1         9E   N348PQ               3281              13487    MSP   
2         9E   N8896A               3282              11433    DTW   
3         9E   N8886A               3283              15249    TLH   
4         9E   N8974C               3284              10397    ATL   

   DEST_AIRPORT_ID DEST  DEP_TIME  DEP_DEL15 DEP_TIME_BLK  ARR_TIME  \
0            10397  ATL     601.0        0.0    0600-0659     722.0   
1            11193  CVG    1359.0        0.0    1400-1459    1633.0   
2            11193  CVG    1215.0        0.0    1200-1259    1329.0   
3            10397  ATL    1521.0        0.0    1500-1559    1625.0   
4            11778  FSM    1847.0        0.0    1900-1959    1940.0   

   ARR_DEL15  CANCELLED  DIVERTED  DISTANCE  
0        0.0          0         0       300  
1        0.0          0         0       596  
2        0.0          0         0       229  
3        0.0          0         0       223  
4        0.0          0         0       579

In [8]:
df.tail() #digunakan untuk menampilkan data paling bawah

DAY_OF_MONTH  DAY_OF_WEEK OP_UNIQUE_CARRIER  OP_CARRIER_AIRLINE_ID  \
583980            31            4                UA                  19977   
583981            31            4                UA                  19977   
583982            31            4                UA                  19977   
583983            31            4                UA                  19977   
583984            31            4                UA                  19977   

       OP_CARRIER TAIL_NUM  OP_CARRIER_FL_NUM  ORIGIN_AIRPORT_ID ORIGIN  \
583980         UA   N776UA                200              12016    GUM   
583981         UA   N36280                174              12016    GUM   
583982         UA   N36280                117              14955    SPN   
583983         UA   N39726                105              14955    SPN   
583984         UA   N39726                104              12016    GUM   

        DEST_AIRPORT_ID DEST  DEP_TIME  DEP_DEL15 DEP_TIME_BLK  ARR_TIME  \
583980            12173  HNL     749.0        0.0    0700-0759    1832.0   
583981            14955  SPN     717.0        0.0    0700-0759     759.0   
583982            12016  GUM     857.0        0.0    0900-0959     933.0   
583983            12016  GUM    1820.0        0.0    1800-1859    1854.0   
583984            14955  SPN    1636.0        0.0    1600-1659    1719.0   

        ARR_DEL15  CANCELLED  DIVERTED  DISTANCE  
583980        0.0          0         0      3801  
583981        0.0          0         0       129  
583982        0.0          0         0       129  
583983        0.0          0         0       129  
583984        0.0          0         0       129

In [9]:
# view summary of dataset

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 583985 entries, 0 to 583984
Data columns (total 19 columns):
 #   Column                 Non-Null Count   Dtype  
---  ------                 --------------   -----  
 0   DAY_OF_MONTH           583985 non-null  int64  
 1   DAY_OF_WEEK            583985 non-null  int64  
 2   OP_UNIQUE_CARRIER      583985 non-null  object 
 3   OP_CARRIER_AIRLINE_ID  583985 non-null  int64  
 4   OP_CARRIER             583985 non-null  object 
 5   TAIL_NUM               581442 non-null  object 
 6   OP_CARRIER_FL_NUM      583985 non-null  int64  
 7   ORIGIN_AIRPORT_ID      583985 non-null  int64  
 8   ORIGIN                 583985 non-null  object 
 9   DEST_AIRPORT_ID        583985 non-null  int64  
 10  DEST                   583985 non-null  object 
 11  DEP_TIME               567633 non-null  float64
 12  DEP_DEL15              567630 non-null  float64
 13  DEP_TIME_BLK           583985 non-null  object 
 14  ARR_TIME               566924 non-nu

In [10]:
# menemukan variabel kategorikal

categorical = [var for var in df.columns if df[var].dtype=='O']

print('There are {} categorical variables\n'.format(len(categorical)))

print('The categorical variables are :\n\n', categorical)

There are 6 categorical variables

The categorical variables are :

 ['OP_UNIQUE_CARRIER', 'OP_CARRIER', 'TAIL_NUM', 'ORIGIN', 'DEST', 'DEP_TIME_BLK']


In [11]:
# mencari nilai yang hilang dari vaiabel kategori

df[categorical].isnull().sum()

OP_UNIQUE_CARRIER       0
OP_CARRIER              0
TAIL_NUM             2543
ORIGIN                  0
DEST                    0
DEP_TIME_BLK            0
dtype: int64

In [12]:
# Melihat jumlah frekuensi nilai dalam variabel kategori

for var in categorical: 
    
    print(df[var].value_counts())

WN    111312
AA     77017
DL     73836
OO     64926
UA     46915
YX     25755
MQ     25699
B6     24443
OH     23169
AS     20744
9E     20198
YV     18346
NK     15222
EV     13195
F9      9647
HA      6798
G4      6763
Name: OP_UNIQUE_CARRIER, dtype: int64
WN    111312
AA     77017
DL     73836
OO     64926
UA     46915
YX     25755
MQ     25699
B6     24443
OH     23169
AS     20744
9E     20198
YV     18346
NK     15222
EV     13195
F9      9647
HA      6798
G4      6763
Name: OP_CARRIER, dtype: int64
N488HA    361
N481HA    348
N483HA    346
N489HA    344
N493HA    328
         ... 
N639VA      1
N271AY      1
N642UA      1
N662UA      1
N2142U      1
Name: TAIL_NUM, Length: 5446, dtype: int64
ATL    31155
ORD    26216
DFW    23063
CLT    19100
DEN    18507
       ...  
PPG       11
HGR       10
ADK        9
OWB        9
OGD        8
Name: ORIGIN, Length: 346, dtype: int64
ATL    31151
ORD    26212
DFW    23078
CLT    19105
DEN    18498
       ...  
PPG       11
HGR       10
ADK  

In [13]:
# melihat distribusi frekuensi variabel kategori

for var in categorical: 
    
    print(df[var].value_counts()/np.float(len(df)))

WN    0.190608
AA    0.131882
DL    0.126435
OO    0.111178
UA    0.080336
YX    0.044102
MQ    0.044006
B6    0.041856
OH    0.039674
AS    0.035521
9E    0.034587
YV    0.031415
NK    0.026066
EV    0.022595
F9    0.016519
HA    0.011641
G4    0.011581
Name: OP_UNIQUE_CARRIER, dtype: float64
WN    0.190608
AA    0.131882
DL    0.126435
OO    0.111178
UA    0.080336
YX    0.044102
MQ    0.044006
B6    0.041856
OH    0.039674
AS    0.035521
9E    0.034587
YV    0.031415
NK    0.026066
EV    0.022595
F9    0.016519
HA    0.011641
G4    0.011581
Name: OP_CARRIER, dtype: float64
N488HA    0.000618
N481HA    0.000596
N483HA    0.000592
N489HA    0.000589
N493HA    0.000562
            ...   
N639VA    0.000002
N271AY    0.000002
N642UA    0.000002
N662UA    0.000002
N2142U    0.000002
Name: TAIL_NUM, Length: 5446, dtype: float64
ATL    0.053349
ORD    0.044892
DFW    0.039492
CLT    0.032706
DEN    0.031691
         ...   
PPG    0.000019
HGR    0.000017
ADK    0.000015
OWB    0.000015
OGD

In [14]:
# check labels in OP_UNIQUE_CARRIER variable

df.OP_UNIQUE_CARRIER.unique()

array(['9E', 'AA', 'MQ', 'G4', 'OH', 'B6', 'YV', 'EV', 'F9', 'YX', 'HA',
       'NK', 'OO', 'WN', 'AS', 'UA', 'DL'], dtype=object)

In [15]:
# check frequency distribution of values in OP_UNIQUE_CARRIER variable

df.OP_UNIQUE_CARRIER.value_counts()

WN    111312
AA     77017
DL     73836
OO     64926
UA     46915
YX     25755
MQ     25699
B6     24443
OH     23169
AS     20744
9E     20198
YV     18346
NK     15222
EV     13195
F9      9647
HA      6798
G4      6763
Name: OP_UNIQUE_CARRIER, dtype: int64

In [16]:
# check labels in OP_CARRIER variable

df.OP_CARRIER.unique()

array(['9E', 'AA', 'MQ', 'G4', 'OH', 'B6', 'YV', 'EV', 'F9', 'YX', 'HA',
       'NK', 'OO', 'WN', 'AS', 'UA', 'DL'], dtype=object)

In [17]:
# check frequency distribution of values in OP_CARRIER variable

df.OP_CARRIER.value_counts()

WN    111312
AA     77017
DL     73836
OO     64926
UA     46915
YX     25755
MQ     25699
B6     24443
OH     23169
AS     20744
9E     20198
YV     18346
NK     15222
EV     13195
F9      9647
HA      6798
G4      6763
Name: OP_CARRIER, dtype: int64

In [18]:
# check labels in TAIL_NUM variable

df.TAIL_NUM.unique()

array(['N8688C', 'N348PQ', 'N8896A', ..., 'N8847A', 'N818NW', 'N15969'],
      dtype=object)

In [19]:
# check frequency distribution of values in TAIL_NUM variable

df.TAIL_NUM.value_counts()

N488HA    361
N481HA    348
N483HA    346
N489HA    344
N493HA    328
         ... 
N639VA      1
N271AY      1
N642UA      1
N662UA      1
N2142U      1
Name: TAIL_NUM, Length: 5446, dtype: int64

In [20]:
#mengecek nilai yang hilang di variabel kategori
df[categorical].isnull().sum()

OP_UNIQUE_CARRIER       0
OP_CARRIER              0
TAIL_NUM             2543
ORIGIN                  0
DEST                    0
DEP_TIME_BLK            0
dtype: int64

In [21]:
# menemukan variabel numerik

numerical = [var for var in df.columns if df[var].dtype!='O']

print('There are {} numerical variables\n'.format(len(numerical)))

print('The numerical variables are :', numerical)

There are 13 numerical variables

The numerical variables are : ['DAY_OF_MONTH', 'DAY_OF_WEEK', 'OP_CARRIER_AIRLINE_ID', 'OP_CARRIER_FL_NUM', 'ORIGIN_AIRPORT_ID', 'DEST_AIRPORT_ID', 'DEP_TIME', 'DEP_DEL15', 'ARR_TIME', 'ARR_DEL15', 'CANCELLED', 'DIVERTED', 'DISTANCE']


In [22]:
# menampilkan variable numerik

df[numerical].head()

DAY_OF_MONTH  DAY_OF_WEEK  OP_CARRIER_AIRLINE_ID  OP_CARRIER_FL_NUM  \
0             1            2                  20363               3280   
1             1            2                  20363               3281   
2             1            2                  20363               3282   
3             1            2                  20363               3283   
4             1            2                  20363               3284   

   ORIGIN_AIRPORT_ID  DEST_AIRPORT_ID  DEP_TIME  DEP_DEL15  ARR_TIME  \
0              11953            10397     601.0        0.0     722.0   
1              13487            11193    1359.0        0.0    1633.0   
2              11433            11193    1215.0        0.0    1329.0   
3              15249            10397    1521.0        0.0    1625.0   
4              10397            11778    1847.0        0.0    1940.0   

   ARR_DEL15  CANCELLED  DIVERTED  DISTANCE  
0        0.0          0         0       300  
1        0.0          0         0       596  
2        0.0          0         0       229  
3        0.0          0         0       223  
4        0.0          0         0       579

In [23]:
#cek nilai yang hilang dari variabel numerik

df[numerical].isnull().sum()

DAY_OF_MONTH                 0
DAY_OF_WEEK                  0
OP_CARRIER_AIRLINE_ID        0
OP_CARRIER_FL_NUM            0
ORIGIN_AIRPORT_ID            0
DEST_AIRPORT_ID              0
DEP_TIME                 16352
DEP_DEL15                16355
ARR_TIME                 17061
ARR_DEL15                18022
CANCELLED                    0
DIVERTED                     0
DISTANCE                     0
dtype: int64

In [24]:
# check labels in DEP_TIME variable

df.DEP_TIME.unique()

array([ 601., 1359., 1215., ...,  232.,  415.,  336.])

In [25]:
# check frequency distribution of values in DEP_TIME variable

df.DEP_TIME.value_counts()

555.0    1382
557.0    1237
556.0    1205
554.0    1191
558.0    1136
         ... 
421.0       1
234.0       1
324.0       1
431.0       1
336.0       1
Name: DEP_TIME, Length: 1438, dtype: int64

In [26]:
# replace '?' values in DEP_TIME variable with `NaN`

df['DEP_TIME'].replace('?', np.NaN, inplace=True)

In [27]:
# check labels in DEP_DEL15 variable

df.DEP_DEL15.unique()

array([ 0.,  1., nan])

In [28]:
# check frequency distribution of values in DEP_DEL15 variable

df.DEP_DEL15.value_counts()

0.0    468703
1.0     98927
Name: DEP_DEL15, dtype: int64

In [29]:
# replace '?' values in DEP_DEL15 variable with `NaN`

df['DEP_DEL15'].replace('?', np.NaN, inplace=True)

In [30]:
# check labels in ARR_TIME variable

df.ARR_TIME.unique()

array([ 722., 1633., 1329., ...,  342.,  305.,  326.])

In [31]:
# check labels in ARR_DEL15 variable

df.ARR_DEL15.unique()

array([ 0.,  1., nan])

In [32]:
# check frequency distribution of values in ARR_DEL15 variable

df.ARR_DEL15.value_counts()

0.0    460741
1.0    105222
Name: ARR_DEL15, dtype: int64

In [33]:
# replace '?' values in DEP_DEL15 variable with `NaN`

df['DEP_DEL15'].replace('?', np.NaN, inplace=True)

In [34]:
#Variabel target
X = df.drop(['CANCELLED'], axis=1)

y = df['CANCELLED']

In [35]:
# split X and y into training and testing sets

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, random_state = 0)

In [36]:
# check the shape of X_train and X_test

X_train.shape, X_test.shape

((408789, 18), (175196, 18))

In [37]:
# check data types in X_train

X_train.dtypes

DAY_OF_MONTH               int64
DAY_OF_WEEK                int64
OP_UNIQUE_CARRIER         object
OP_CARRIER_AIRLINE_ID      int64
OP_CARRIER                object
TAIL_NUM                  object
OP_CARRIER_FL_NUM          int64
ORIGIN_AIRPORT_ID          int64
ORIGIN                    object
DEST_AIRPORT_ID            int64
DEST                      object
DEP_TIME                 float64
DEP_DEL15                float64
DEP_TIME_BLK              object
ARR_TIME                 float64
ARR_DEL15                float64
DIVERTED                   int64
DISTANCE                   int64
dtype: object

In [38]:
# display categorical variables

categorical = [col for col in X_train.columns if X_train[col].dtypes == 'O']

categorical

['OP_UNIQUE_CARRIER',
 'OP_CARRIER',
 'TAIL_NUM',
 'ORIGIN',
 'DEST',
 'DEP_TIME_BLK']

In [39]:
# display numerical variables

numerical = [col for col in X_train.columns if X_train[col].dtypes != 'O']

numerical

['DAY_OF_MONTH',
 'DAY_OF_WEEK',
 'OP_CARRIER_AIRLINE_ID',
 'OP_CARRIER_FL_NUM',
 'ORIGIN_AIRPORT_ID',
 'DEST_AIRPORT_ID',
 'DEP_TIME',
 'DEP_DEL15',
 'ARR_TIME',
 'ARR_DEL15',
 'DIVERTED',
 'DISTANCE']

In [40]:
# check missing values in X_train

# print percentage of missing values in the categorical variables in training set

X_train[categorical].isnull().mean()

OP_UNIQUE_CARRIER    0.000000
OP_CARRIER           0.000000
TAIL_NUM             0.004374
ORIGIN               0.000000
DEST                 0.000000
DEP_TIME_BLK         0.000000
dtype: float64

In [41]:
# impute missing categorical variables with most frequent value

for df2 in [X_train, X_test]:
    df2['TAIL_NUM'].fillna(X_train['TAIL_NUM'].mode()[0], inplace=True)

In [42]:
# check missing values in categorical variables in X_train

X_train[categorical].isnull().sum()

OP_UNIQUE_CARRIER    0
OP_CARRIER           0
TAIL_NUM             0
ORIGIN               0
DEST                 0
DEP_TIME_BLK         0
dtype: int64

In [43]:
# check missing values in categorical variables in X_test

X_test[categorical].isnull().sum()

OP_UNIQUE_CARRIER    0
OP_CARRIER           0
TAIL_NUM             0
ORIGIN               0
DEST                 0
DEP_TIME_BLK         0
dtype: int64

In [44]:
# impute missing numerical variables with most frequent value

for df2 in [X_train, X_test]:
    df2['DEP_TIME'].fillna(X_train['DEP_TIME'].mode()[0], inplace=True)
    df2['DEP_DEL15'].fillna(X_train['DEP_DEL15'].mode()[0], inplace=True)
    df2['ARR_TIME'].fillna(X_train['ARR_TIME'].mode()[0], inplace=True)
    df2['ARR_DEL15'].fillna(X_train['ARR_DEL15'].mode()[0], inplace=True)


In [45]:
# check missing values in X_train

X_train.isnull().sum()

DAY_OF_MONTH             0
DAY_OF_WEEK              0
OP_UNIQUE_CARRIER        0
OP_CARRIER_AIRLINE_ID    0
OP_CARRIER               0
TAIL_NUM                 0
OP_CARRIER_FL_NUM        0
ORIGIN_AIRPORT_ID        0
ORIGIN                   0
DEST_AIRPORT_ID          0
DEST                     0
DEP_TIME                 0
DEP_DEL15                0
DEP_TIME_BLK             0
ARR_TIME                 0
ARR_DEL15                0
DIVERTED                 0
DISTANCE                 0
dtype: int64

In [46]:
# check missing values in X_test

X_test.isnull().sum()

DAY_OF_MONTH             0
DAY_OF_WEEK              0
OP_UNIQUE_CARRIER        0
OP_CARRIER_AIRLINE_ID    0
OP_CARRIER               0
TAIL_NUM                 0
OP_CARRIER_FL_NUM        0
ORIGIN_AIRPORT_ID        0
ORIGIN                   0
DEST_AIRPORT_ID          0
DEST                     0
DEP_TIME                 0
DEP_DEL15                0
DEP_TIME_BLK             0
ARR_TIME                 0
ARR_DEL15                0
DIVERTED                 0
DISTANCE                 0
dtype: int64

In [47]:
X_train[categorical].head()

OP_UNIQUE_CARRIER OP_CARRIER TAIL_NUM ORIGIN DEST DEP_TIME_BLK
573892                OH         OH   N228PS    BDL  DCA    1100-1159
568051                YX         YX   N109HQ    PIT  LGA    0700-0759
519259                YX         YX   N860RW    IND  BOS    1100-1159
492246                NK         NK   N673NK    DTW  RSW    0600-0659
302010                UA         UA   N69816    LAX  ORD    0800-0859

In [48]:
# import category encoders

import category_encoders as ce

In [ ]:
# encode remaining variables with one-hot encoding

encoder = ce.OneHotEncoder(cols=['OP_UNIQUE_CARRIER','OP_CARRIER','TAIL_NUM','ORIGIN','DEST','DEP_TIME_BLK'])

X_train = encoder.fit_transform(X_train)

X_test = encoder.transform(X_test)

In [ ]:
X_train.head()

In [ ]:
X_train.shape

In [ ]:
X_test.head()

In [ ]:
X_test.shape

In [ ]:
cols = X_train.columns

In [ ]:
from sklearn.preprocessing import RobustScaler

scaler = RobustScaler()

X_train = scaler.fit_transform(X_train)

X_test = scaler.transform(X_test)

In [ ]:
X_train = pd.DataFrame(X_train, columns=[cols])

In [ ]:
X_test = pd.DataFrame(X_test, columns=[cols])

In [ ]:
X_train.head()